//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Binom.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_BINOM_H)
#define _BINOM_H

#include "Factorial.h"

class Binom {
public:
	double calculate(int n, int k);
	void <<create>>Binom();
	void <<destroy>>Binom();
private:
	Factorial pFactorial;
};

#endif  //_BINOM_H
