//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Binom.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Binom.h"

double Binom::calculate(int n, int k) {
    return (double)pFactorial.getResult(n)/(double)(pFactorial.getResult(k)*pFactorial.getResult(n - k));
}

void Binom::<<create>>Binom() {
    pFactorial = new Factorial;
}

void Binom::<<destroy>>Binom() {
    delete pFactorial;
}

