//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Power.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Power.h"

int Power::calculate(int num, int pow) {
    for(int i = 1; i < pow; i++){
        num*=num;
    }
    return num;
}

