//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Power.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_POWER_H)
#define _POWER_H


class Power {
public:
	int calculate(int num, int pow);
};

#endif  //_POWER_H
