//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Probability.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_PROBABILITY_H)
#define _PROBABILITY_H

#include "Binom.h"
#include "Power.h"

class Probability {
public:
	double calcBern(int n, int k, int p);
	void <<create>>Probability();
	void <<destroy>>Probability();
private:
	Binom pBinom;
	Power pPower;
};

#endif  //_PROBABILITY_H
