//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Probability.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Probability.h"

double Probability::calcBern(int n, int k, int p) {
    double q = 1 - p;

    return pBinom.calculate(n,k) * pPower.calculate(p,k) * pPower.calculate(q,n-k);
}

void Probability::<<create>>Probability() {
    pBinom = new Binom;
	pPower = new Power;
}

void Probability::<<destroy>>Probability() {
    delete pBinom;
    delete pPower;
}

