//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bae, Rankyoung.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_BAE, RANKYOUNG_H)
#define _BAE, RANKYOUNG_H

#include "Lim, Heejin.h"

class Bae, Rankyoung : public Lim, Heejin {
};

#endif  //_BAE, RANKYOUNG_H
