//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Lim, Heejin.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_LIM, HEEJIN_H)
#define _LIM, HEEJIN_H


class Lim, Heejin {
};

#endif  //_LIM, HEEJIN_H
