//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLibrary.cpp
//  @ Date : 05.03.2018
//  @ Author :
//
//


#include "TLibrary.h"

void TLibrary::printData() {
    cout<<this->
}

void TLibrary::setData(string title, string mark) {

}

TLibrary::TLibrary(string libName) {

}

TLibrary::~TLibrary() {

}

