//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//

#include <vector>
#include "TUniversity.h"

void TUniversity::attach() {
    if(students.size() < 6)
        students.push_back(new TStudent);
}

void TUniversity::detach() {
    if( !students.empty() )
        students.pop_back();
}

TUniversity::TUniversity(){
    this->students.reserve(5);
}

