//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 05.03.2018
//  @ Author :
//
//


#include "TUniversity.h"

TUniversity::TUniversity(string univName) {
    this->name = univName;
}

void TUniversity::printData() {
    cout<<"Uczelnia - "<<this->name
    <<"\nStudent - "<<this->student.getName()
    <<" ma lat - "<<this->student.getAge();
}

void TUniversity::setData(string name, int age) {
    this->student.setAge(age);
    this->student.setName(name);
}

