//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//


#include "TUniversity.h"

void TUniversity::attach(TStudent st) {
    students.push_back(st);
}

void TUniversity::detach() {
    students.pop_back();
}

void TUniversity::printData(int i) {
    cout<<students[i]->studentName<<" "<<students[i]->studentAge;
}

void TUniversity::satData(int i, string name, int age) {
    students[i]->studentName = name;
    students[i]->studentAge = age;
}

